apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fiap-cloud-games
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=gamesdb;Username=admin;Password=123456"
